/**
 * The whole of `sync:upstream`'s generation step, as one pure function.
 *
 * `planOutputs` takes the raw text of every upstream file the site derives
 * from and returns the exact bytes of every file the sync writes. The impure
 * shell (`scripts/sync-upstream.ts`) only fetches, reads, and writes — it
 * makes no decisions about content. That split is what makes `--check` a
 * true drift detector and what makes the pipeline testable without a
 * checkout or a network.
 */

import {
	BLOB_BASE,
	RAW_BASE,
	UPSTREAM,
	UPSTREAM_DOCS,
	type UpstreamDoc,
} from "../../src/config/upstream.ts";
import { type CliCommand, parseCommands, parseProgramDescription } from "./cli.ts";
import { renderCliReference } from "./cli-page.ts";
import { buildFacts, renderFacts } from "./facts.ts";
import {
	deriveDescription,
	labelEmptyTableHeaders,
	renderPage,
	rewriteLinks,
	stripLeadingH1,
} from "./markdown.ts";
import { renderThemeCss, TOKENS_OUT_PATH, TOKENS_SOURCE } from "./tokens.ts";

/** Upstream path of the commander entry point the CLI reference derives from. */
export const CLI_SOURCE = "src/cli/main.ts";

/** Every non-narrative upstream file the sync reads, keyed by its role. */
export const EXTRA_SOURCES = {
	cliMain: CLI_SOURCE,
	packageJson: "package.json",
	openapi: "docs/openapi.yaml",
	dockerfile: "Dockerfile",
	envExample: ".env.example",
	k8sDeployment: "deploy/k8s/base/deployment.yaml",
	themeCss: TOKENS_SOURCE,
} as const;

export const DOCS_OUT_DIR = "src/content/docs/docs";
export const CLI_OUT_PATH = `${DOCS_OUT_DIR}/reference/cli.md`;
export const FACTS_OUT_PATH = "src/config/facts.generated.json";
export const THEME_OUT_PATH = TOKENS_OUT_PATH;

/**
 * Substring every generated Markdown page carries. `--check` uses it to tell
 * a derived page apart from a hand-written one, so a page dropped from
 * `UPSTREAM_DOCS` can be pruned without touching authored content.
 */
export const GENERATED_MARKER = "GENERATED by `bun run sync:upstream`";

export type UpstreamSources = {
	/** Upstream path -> file text, for every entry in `UPSTREAM_DOCS`. */
	readonly docs: ReadonlyMap<string, string>;
	readonly cliMain: string;
	readonly packageJson: string;
	readonly openapi: string;
	readonly dockerfile: string;
	readonly envExample: string;
	readonly k8sDeployment: string;
	/** Raw text of warren's `src/ui/src/index.css`, source of the design tokens. */
	readonly themeCss: string;
};

export type GeneratedFile = {
	/** Path relative to the repository root. */
	readonly path: string;
	readonly content: string;
};

/** The banner comment at the top of every generated Markdown page. */
export function generatedBanner(source: string): string {
	return (
		`<!-- ${GENERATED_MARKER} from ` +
		`${UPSTREAM.owner}/${UPSTREAM.repo}@${UPSTREAM.ref} (${source}). ` +
		"DO NOT EDIT — change it upstream and re-sync. -->"
	);
}

function renderNarrativePage(
	doc: UpstreamDoc,
	raw: string,
	slugBySource: ReadonlyMap<string, string>,
): string {
	const stripped = stripLeadingH1(raw);
	const linked = rewriteLinks(stripped, {
		sourcePath: doc.source,
		slugBySource,
		blobBase: BLOB_BASE,
		rawBase: RAW_BASE,
	});
	// Last, so it sees the final cell text and cannot disturb link rewriting.
	const body = labelEmptyTableHeaders(linked);
	return renderPage({
		title: doc.title,
		description: deriveDescription(stripped),
		editUrl: `${BLOB_BASE}/${doc.source}`,
		banner: generatedBanner(doc.source),
		body,
	});
}

function renderCliPage(commands: readonly CliCommand[], cliMain: string): string {
	const sourceUrl = `${BLOB_BASE}/${CLI_SOURCE}`;
	return renderPage({
		title: "CLI reference",
		description:
			`Every \`warren\` subcommand at ${UPSTREAM.ref}, ` +
			`extracted from the command definitions in ${CLI_SOURCE}.`,
		editUrl: sourceUrl,
		banner: generatedBanner(CLI_SOURCE),
		body: renderCliReference({
			commands,
			programDescription: parseProgramDescription(cliMain),
			sourceUrl,
		}),
	});
}

/** Every upstream path the sync reads: the narrative docs plus `EXTRA_SOURCES`. */
export function allSourcePaths(): string[] {
	return [...UPSTREAM_DOCS.map((doc) => doc.source), ...Object.values(EXTRA_SOURCES)];
}

/** Which manifest entry names `path`, for the missing-source report. */
function sourceRole(path: string): string {
	const doc = UPSTREAM_DOCS.find((entry) => entry.source === path);
	if (doc !== undefined) return `UPSTREAM_DOCS -> ${DOCS_OUT_DIR}/${doc.slug}.md`;
	const extra = Object.entries(EXTRA_SOURCES).find(([, source]) => source === path);
	return extra === undefined ? "not in the manifest" : `EXTRA_SOURCES.${extra[0]}`;
}

/**
 * One actionable report naming EVERY missing source. When warren reshuffles
 * its docs tree, several manifest entries break at once; throwing on the
 * first would turn one upstream change into a fix-rerun-fix loop, so the
 * sync collects the whole set and fails once.
 */
export function missingSourcesReport(missing: readonly string[]): string {
	return [
		`sync:upstream: ${missing.length} source file(s) named by the manifest are absent from ` +
			`${UPSTREAM.owner}/${UPSTREAM.repo}@${UPSTREAM.ref}:`,
		...missing.map((path) => `  - ${path}  (${sourceRole(path)})`),
		"Warren renamed, moved, or deleted these files. Fix every entry above in ONE pass —",
		"UPSTREAM_DOCS lives in src/config/upstream.ts, EXTRA_SOURCES in scripts/upstream/plan.ts —",
		"then re-run: bun run sync:upstream",
	].join("\n");
}

/** Every path this sync owns, in write order. Used by `--check` to find orphans. */
export function expectedOutputPaths(): string[] {
	return [
		...UPSTREAM_DOCS.map((doc) => `${DOCS_OUT_DIR}/${doc.slug}.md`),
		CLI_OUT_PATH,
		FACTS_OUT_PATH,
		THEME_OUT_PATH,
	];
}

/**
 * Generate every derived file. Throws — loudly — rather than emitting an
 * empty or partial artifact: a missing upstream file means the manifest and
 * the pinned ref disagree, a CLI parse that finds nothing means the
 * extractor's assumptions about `src/cli/main.ts` have expired, and a token
 * block that cannot be found means warren's stylesheet was restructured. All
 * three are worse silently than as a failed build.
 */
export function planOutputs(sources: UpstreamSources): GeneratedFile[] {
	const missing = UPSTREAM_DOCS.filter((doc) => !sources.docs.has(doc.source));
	if (missing.length > 0) {
		throw new Error(missingSourcesReport(missing.map((doc) => doc.source)));
	}
	const slugBySource = new Map(UPSTREAM_DOCS.map((doc) => [doc.source, doc.slug] as const));
	const files: GeneratedFile[] = [];
	for (const doc of UPSTREAM_DOCS) {
		const raw = sources.docs.get(doc.source);
		if (raw === undefined) continue; // unreachable: the aggregate check above threw
		files.push({
			path: `${DOCS_OUT_DIR}/${doc.slug}.md`,
			content: renderNarrativePage(doc, raw, slugBySource),
		});
	}

	const commands = parseCommands(sources.cliMain);
	if (commands.length === 0) {
		throw new Error(
			`sync:upstream: the CLI extractor found no commands in ${CLI_SOURCE}. Refusing to ` +
				"write an empty reference — the .command(...) chains have been restructured " +
				"upstream and scripts/upstream/cli.ts needs updating.",
		);
	}
	files.push({ path: CLI_OUT_PATH, content: renderCliPage(commands, sources.cliMain) });
	files.push({
		path: FACTS_OUT_PATH,
		content: renderFacts(
			buildFacts({
				ref: UPSTREAM.ref,
				packageJson: sources.packageJson,
				openapiYaml: sources.openapi,
				dockerfile: sources.dockerfile,
				envExample: sources.envExample,
				k8sDeployment: sources.k8sDeployment,
				commands,
			}),
		),
	});
	files.push({
		path: THEME_OUT_PATH,
		content: renderThemeCss(sources.themeCss, {
			ref: UPSTREAM.ref,
			repoLabel: `${UPSTREAM.owner}/${UPSTREAM.repo}`,
			sourcePath: EXTRA_SOURCES.themeCss,
		}),
	});
	return files;
}
