// @ts-check
import { existsSync } from "node:fs";
import { fileURLToPath } from "node:url";

import starlight from "@astrojs/starlight";
import { defineConfig } from "astro/config";
import starlightLinksValidator from "starlight-links-validator";
import starlightLlmsTxt from "starlight-llms-txt";
import starlightOpenAPI, { createOpenAPISidebarGroup } from "starlight-openapi";
import { createStarlightTypeDocPlugin } from "starlight-typedoc";

import { BLOB_BASE, OPENAPI_URL, UPSTREAM } from "./src/config/upstream.ts";

const root = new URL("./", import.meta.url);

/** Absolute path helper so the `.upstream/` probes are cwd-independent. */
const fromRoot = (/** @type {string} */ path) => fileURLToPath(new URL(path, root));

/**
 * The SDK reference is generated by TypeDoc from a checkout of warren at
 * the pinned ref, produced by `bun run sync:upstream`. That checkout is
 * gitignored and absent on a fresh clone, so registering the plugin
 * unconditionally would fail every first build.
 *
 * Probe for the entry point AND the tsconfig TypeDoc compiles against; if
 * either is missing, skip the plugin (and its sidebar group) and warn.
 * `/docs/sdk/` is then simply absent from the build — no broken links,
 * because the sidebar group is dropped with it.
 */
const TYPEDOC_ENTRY_POINT = ".upstream/src/client/index.ts";
const TYPEDOC_TSCONFIG = ".upstream/tsconfig.json";

const hasUpstreamCheckout =
	existsSync(fromRoot(TYPEDOC_ENTRY_POINT)) && existsSync(fromRoot(TYPEDOC_TSCONFIG));

const [starlightTypeDoc, typeDocSidebarGroup] = createStarlightTypeDocPlugin();
const openAPISidebarGroup = createOpenAPISidebarGroup();

/**
 * The API reference renders from the SAME `.upstream/` checkout every
 * other derived surface reads, not from a network fetch of the pinned
 * ref — `sync:upstream` already guarantees `docs/openapi.yaml` exists
 * there. The raw.githubusercontent URL survives only as the fallback for
 * a fresh clone that has never run the sync (the same degraded mode in
 * which the SDK reference is skipped above), so `bun run build` keeps
 * working before the first sync.
 */
const OPENAPI_LOCAL = ".upstream/docs/openapi.yaml";
const openApiSchema = existsSync(fromRoot(OPENAPI_LOCAL)) ? OPENAPI_LOCAL : OPENAPI_URL;

if (!hasUpstreamCheckout) {
	console.warn(
		`[warren-site] No upstream checkout at ./.upstream — skipping the SDK reference.\n` +
			`[warren-site]   expected: ${TYPEDOC_ENTRY_POINT} + ${TYPEDOC_TSCONFIG}\n` +
			`[warren-site]   fix: bun run sync:upstream   (clones ${UPSTREAM.owner}/${UPSTREAM.repo} @ ${UPSTREAM.ref})\n` +
			`[warren-site]   /docs/sdk/ will NOT be present in this build.`,
	);
}

/**
 * The SDK reference plugin, registered only when `.upstream/` is present.
 * @type {import('@astrojs/starlight/types').StarlightPlugin[]}
 */
const typeDocPlugins = hasUpstreamCheckout
	? [
			starlightTypeDoc({
				entryPoints: [TYPEDOC_ENTRY_POINT],
				tsconfig: TYPEDOC_TSCONFIG,
				// Relative to `src/content/docs/`, so this renders at /docs/sdk/.
				output: "docs/sdk",
				sidebar: { label: "SDK", collapsed: true },
				typeDoc: {
					// The upstream checkout has no README worth inlining here.
					readme: "none",
					gitRevision: UPSTREAM.ref,
					/**
					 * REQUIRED — without it a fresh checkout cannot build.
					 *
					 * `sync:upstream` clones warren at the pinned ref and
					 * deliberately never runs `bun install` inside `.upstream/`
					 * (see the header of `scripts/sync-upstream.ts`). TypeDoc
					 * builds its program from `.upstream/tsconfig.json`, which
					 * includes the whole source tree, so every `import "pino"`,
					 * `"croner"`, `"@os-eco/burrow-cli"` in warren raises TS2307
					 * against an empty `node_modules` and the plugin aborts the
					 * build. Skipping the semantic-diagnostics pass makes TypeDoc
					 * read declarations without resolving warren's runtime
					 * dependencies.
					 *
					 * This costs nothing here: the SDK page documents the shapes
					 * `.upstream/src/client/index.ts` exports, and type-CHECKING
					 * warren is warren's own CI's job, not this site's. Do not
					 * "fix" a TS2307 from `.upstream/` by installing there — a
					 * 300MB install would land on every CI run and on every
					 * contributor's first build.
					 */
					skipErrorChecking: true,
				},
			}),
		]
	: [];

export default defineConfig({
	site: "https://warren.run",
	/**
	 * Off deliberately. Starlight otherwise defaults it to
	 * `{ prefetchAll: true }`, and Astro's prefetch runtime is injected as a
	 * page script into EVERY route — including the landing page and
	 * `/changelog`, which are required to ship zero client JavaScript. Flip
	 * this back on if that requirement is ever relaxed; docs navigation is
	 * the only thing that gains from it.
	 */
	prefetch: false,
	integrations: [
		starlight({
			title: "Warren",
			description:
				"Self-hostable control plane for ephemeral cloud agents. Point it at a repo, pick an agent, get a pull request.",
			/**
			 * No `logo` here on purpose. That option takes an image path, and
			 * the lockup is now an inline SVG so it can be transparent and
			 * follow the theme — see the header of `WarrenLogo.astro`. The
			 * `SiteTitle` override below renders it instead, which also
			 * removes the `alt=""` / `replacesTitle` dance the raster needed
			 * to keep axe's `image-redundant-alt` quiet.
			 */
			components: {
				SiteTitle: "./src/components/StarlightSiteTitle.astro",
			},
			favicon: "/favicon.svg",
			social: [
				{ icon: "github", label: "GitHub", href: "https://github.com/jayminwest/warren" },
			],
			/**
			 * Docs on this site are derived from warren at the pinned ref, so
			 * "Edit this page" must land in the upstream repo rather than here.
			 * Starlight appends the local `filePath` to `baseUrl`; pages
			 * generated by `sync:upstream` therefore carry an explicit
			 * `editUrl` in their frontmatter pointing at their true source.
			 * This base is the fallback for hand-written pages.
			 */
			editLink: { baseUrl: `${BLOB_BASE}/` },
			customCss: ["./src/styles/warren-theme.css", "./src/styles/starlight-overrides.css"],
			// Warren's own UI defaults to the OS preference; match it here.
			pagefind: true,
			sidebar: [
				{
					label: "Start here",
					items: [{ slug: "docs/quickstart" }, { slug: "docs/project-setup" }],
				},
				// Starlight >= 0.39 requires `autogenerate` to sit inside `items`
				// rather than alongside a `label`.
				{ label: "Concepts", items: [{ autogenerate: { directory: "docs/concepts" } }] },
				{ label: "Self-host", items: [{ autogenerate: { directory: "docs/self-host" } }] },
				{ label: "Reference", items: [{ autogenerate: { directory: "docs/reference" } }] },
				openAPISidebarGroup,
				...(hasUpstreamCheckout ? [typeDocSidebarGroup] : []),
			],
			plugins: [
				starlightOpenAPI([
					{
						base: "docs/api",
						schema: openApiSchema,
						sidebar: {
							label: "API",
							collapsed: true,
							group: openAPISidebarGroup,
							operations: { badges: true, labels: "path", sort: "alphabetical" },
						},
					},
				]),
				...typeDocPlugins,
				starlightLlmsTxt({
					projectName: "Warren",
					description:
						"Warren is a self-hostable control plane for ephemeral cloud agents. It clones a GitHub repository, runs a coding agent inside a sandbox, streams the run back to an HTTP API and UI, and pushes the resulting branch as a pull request.",
					details: [
						"Notes for models reading these docs:",
						"",
						`- The documentation is generated from jayminwest/warren at tag ${UPSTREAM.ref}. Behaviour on \`main\` may differ.`,
						"- `/docs/api/` is generated from the server's OpenAPI 3.1 schema and is the authoritative HTTP contract.",
						"- `/docs/sdk/` is generated from the TypeScript client's public exports.",
					].join("\n"),
					optionalLinks: [
						{
							label: "warren on GitHub",
							url: "https://github.com/jayminwest/warren",
							description: "Source, issues, and releases.",
						},
					],
				}),
				// Must stay last: it validates the routes every plugin above adds.
				starlightLinksValidator({
					errorOnRelativeLinks: false,
					errorOnLocalLinks: false,
				}),
			],
		}),
	],
});
