/**
 * Word lists and regex fragments for the prose guard (`check-prose.ts`).
 *
 * Split out of the guard itself to keep each file inside the per-file line
 * budget (`scripts/file-size-budgets.json`). This module is pure data — no
 * logic lives here.
 */

export const MARKETING = [
	"seamless",
	"seamlessly",
	"robust",
	"powerful",
	"cutting-edge",
	"effortless",
	"effortlessly",
	"world-class",
	"next-generation",
	"revolutionary",
	"blazing",
	"lightning-fast",
	"turnkey",
	"best-in-class",
	"state-of-the-art",
	"game-changing",
	"battle-tested",
	"enterprise-grade",
	"supercharge",
	"unleash",
	"empower",
];

export const SUBSTITUTE = [
	"utilize",
	"utilizes",
	"utilizing",
	"utilization",
	"leverage",
	"leverages",
	"leveraging",
	"facilitate",
	"facilitates",
	"ensure",
	"ensures",
	"ensuring",
	"commence",
	"commences",
	"initiate",
	"initiates",
	"terminate",
	"terminates",
	"prior to",
	"subsequent to",
	"in order to",
	"due to the fact that",
	"in the event that",
	"additionally",
	"furthermore",
	"moreover",
	"whilst",
	"amongst",
	"myriad",
	"plethora",
	"aforementioned",
	"henceforth",
	"delve into",
	"delves into",
	"it is important to note",
	"it should be noted",
	"it is worth noting",
	"needless to say",
];

export const PHRASAL = [
	"spin up",
	"spins up",
	"spun up",
	"spin down",
	"reach out",
	"reaches out",
	"kick off",
	"kicks off",
	"roll out",
	"rolls out",
	"tear down",
	"tears down",
	"ramp up",
	"ramps up",
	"circle back",
	"drill down",
	"give off",
	"gives off",
];

export const LATIN = ["e.g.", "i.e.", "etc.", "viz.", "cf."];

/** Past participles that STE Rule 3.3 permits as adjectives (not passive). */
export const ADJECTIVAL = new Set([
	"completed",
	"disassembled",
	"assembled",
	"installed",
	"damaged",
	"permitted",
	"enabled",
	"disabled",
	"required",
	"expected",
	"supported",
	"deprecated",
	"reserved",
	"related",
	"limited",
	"detailed",
	"documented",
	"scoped",
	"pinned",
	"frozen",
	"known",
	"done",
	"set",
	"unchanged",
	"sandboxed",
	"authenticated",
	"authorized",
	"encrypted",
	"paused",
	"closed",
	"open",
]);

export const IRREGULAR_PP =
	"done|made|sent|read|built|kept|held|put|run|written|shown|given|taken|found|seen|known|thrown|drawn|torn|lost|left|paid|met|split";

export const BE = "am|is|are|was|were|be|been|being";

/** Real contractions. Everything else ending in `'s` is a possessive, which STE GR-8 permits. */
export const CONTRACTIONS =
	/\b(?:\w+['’](?:t|re|ve|ll|m)|(?:it|that|there|here|what|who|let|he|she|who)['’]s)\b/gi;

/**
 * Words ending in `-ing` that are nouns, adjectives, or prepositions rather
 * than main verbs. STE Rule 3.5 approves several of these outright.
 */
export const ING_NOT_VERB = new Set([
	"nothing",
	"something",
	"anything",
	"everything",
	"during",
	"missing",
	"remaining",
	"mating",
	"lighting",
	"opening",
	"routing",
	"servicing",
	"warning",
	"string",
	"thing",
	"engineering",
	"willing",
	"pending",
	"outstanding",
	"following",
	"existing",
	"working",
	"long-running",
]);

/** Determiners that can open a noun stack. */
export const DETERMINERS = new Set([
	"the",
	"a",
	"an",
	"this",
	"these",
	"those",
	"its",
	"their",
	"each",
	"every",
]);

/** Words that end a noun run: they are verbs, adverbs, or participles, not stack members. */
export const VERBISH = /(?:ly|ing|ed)$/;

/** Words that break a noun stack — if one appears, the run ends. */
export const STOPWORDS = new Set([
	"a",
	"an",
	"the",
	"this",
	"that",
	"these",
	"those",
	"and",
	"or",
	"but",
	"if",
	"when",
	"then",
	"thus",
	"so",
	"of",
	"in",
	"on",
	"at",
	"to",
	"for",
	"with",
	"from",
	"by",
	"as",
	"into",
	"over",
	"under",
	"after",
	"before",
	"is",
	"are",
	"was",
	"were",
	"be",
	"been",
	"being",
	"has",
	"have",
	"had",
	"can",
	"cannot",
	"will",
	"must",
	"not",
	"no",
	"its",
	"it",
	"you",
	"we",
	"they",
	"each",
	"per",
	"via",
	"only",
	"also",
	"both",
	"all",
	"any",
	"do",
	"does",
	"did",
	"use",
	"uses",
	"used",
	"see",
	"refer",
	"one",
	"two",
	"three",
	"new",
	"same",
	"other",
	"plus",
	"either",
	"neither",
	"such",
	"more",
	"most",
	"less",
	"least",
	"than",
	"which",
	"who",
	"where",
	"while",
	"until",
	"unless",
	"because",
	"though",
	"although",
	"however",
	"just",
	"still",
	"yet",
	"now",
	"here",
	"there",
	"out",
	"up",
	"down",
	"off",
	"back",
	"again",
	"once",
	"without",
	"within",
	"across",
	"through",
	"between",
	"among",
	"against",
	"above",
	"below",
	"behind",
	"near",
	"next",
	"first",
	"second",
	"third",
	"last",
	"own",
	"another",
	"many",
	"few",
	"several",
	"some",
	"none",
	"every",
	"may",
	"should",
	"shall",
	"would",
	"could",
	"might",
	"get",
	"gets",
	"let",
	"make",
	"makes",
	"made",
	"goes",
	"go",
	"say",
	"says",
	"need",
	"needs",
	"want",
	"wants",
	"keep",
	"keeps",
	"give",
	"gives",
	"take",
	"takes",
	"put",
	"puts",
]);
