#!/usr/bin/env bun
/**
 * Upstream content pipeline for warren.run.
 *
 * This site documents `jayminwest/warren` and restates nothing by hand.
 * Every page under `/docs/` derives from ONE pinned ref — the manifest in
 * `src/config/upstream.ts`. This script is that derivation.
 *
 *   bun run scripts/sync-upstream.ts            # fetch + regenerate
 *   bun run scripts/sync-upstream.ts --check    # fail on drift (CI)
 *
 * What it writes:
 *   - `src/content/docs/docs/<slug>.md` — one page per `UPSTREAM_DOCS` entry
 *   - `src/content/docs/docs/reference/cli.md` — from warren's commander CLI
 *   - `src/config/facts.generated.json` — the numbers the landing page cites
 *
 * Everything that decides content is a pure function in `scripts/upstream/`
 * and is unit-tested without a checkout. This file is only the shell: clone,
 * read, write, or diff. `--check` compares the regenerated bytes against what
 * is committed and exits 1 with a per-file summary, which is what
 * `gen:docs:check` runs on every PR.
 *
 * The script never runs `bun install` inside `.upstream/`. The CLI reference
 * is extracted statically for exactly that reason — see the header of
 * `scripts/upstream/cli.ts`.
 */

import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";

import { CLONE_URL, UPSTREAM, UPSTREAM_DOCS } from "../src/config/upstream.ts";
import {
	DOCS_OUT_DIR,
	EXTRA_SOURCES,
	expectedOutputPaths,
	GENERATED_MARKER,
	type GeneratedFile,
	planOutputs,
	type UpstreamSources,
} from "./upstream/plan.ts";

const REPO_ROOT = resolve(import.meta.dir, "..");
const CHECKOUT_DIR = resolve(REPO_ROOT, ".upstream");
/** Directories under `DOCS_OUT_DIR` this script must not prune. */
const NON_DERIVED_DIRS = new Set(["sdk", "api"]);
/** How many differing lines `--check` prints per drifted file. */
const DIFF_LINES = 4;

function git(args: readonly string[], cwd: string): { ok: boolean; stdout: string } {
	const result = Bun.spawnSync(["git", ...args], { cwd, stdout: "pipe", stderr: "pipe" });
	return { ok: result.exitCode === 0, stdout: new TextDecoder().decode(result.stdout).trim() };
}

/** True when `.upstream/` is a git checkout whose HEAD is the pinned ref. */
function checkoutIsCurrent(): boolean {
	if (!existsSync(join(CHECKOUT_DIR, ".git"))) return false;
	const head = git(["rev-parse", "HEAD"], CHECKOUT_DIR);
	const pinned = git(
		["rev-parse", "--verify", "--quiet", `${UPSTREAM.ref}^{commit}`],
		CHECKOUT_DIR,
	);
	return head.ok && pinned.ok && head.stdout !== "" && head.stdout === pinned.stdout;
}

/**
 * Shallow-clone the pinned ref into `.upstream/`, reusing an existing
 * checkout when it already sits at that ref. A checkout at the WRONG ref is
 * discarded rather than fetched into: a `--depth 1 --single-branch` clone has
 * no history to move through, and re-cloning is both cheaper and impossible
 * to leave half-updated.
 */
function ensureCheckout(): void {
	if (checkoutIsCurrent()) {
		console.log(`.upstream/ already at ${UPSTREAM.ref}`);
		return;
	}
	if (existsSync(CHECKOUT_DIR)) {
		console.log(`.upstream/ is not at ${UPSTREAM.ref} — re-cloning`);
		rmSync(CHECKOUT_DIR, { recursive: true, force: true });
	}
	console.log(`cloning ${UPSTREAM.owner}/${UPSTREAM.repo}@${UPSTREAM.ref} into .upstream/`);
	const clone = git(
		["clone", "--depth", "1", "--single-branch", "--branch", UPSTREAM.ref, CLONE_URL, CHECKOUT_DIR],
		REPO_ROOT,
	);
	if (!clone.ok || !checkoutIsCurrent()) {
		throw new Error(
			`sync:upstream: could not check out ${UPSTREAM.owner}/${UPSTREAM.repo}@${UPSTREAM.ref}. ` +
				"Verify the ref in src/config/upstream.ts exists and that the network is reachable.",
		);
	}
}

function readCheckoutFile(path: string): string {
	const absolute = join(CHECKOUT_DIR, path);
	if (!existsSync(absolute)) {
		throw new Error(
			`sync:upstream: ${path} is missing from ${UPSTREAM.repo}@${UPSTREAM.ref}. ` +
				"The upstream layout changed; update src/config/upstream.ts or scripts/upstream/plan.ts.",
		);
	}
	return readFileSync(absolute, "utf8");
}

function readSources(): UpstreamSources {
	const docs = new Map<string, string>();
	for (const doc of UPSTREAM_DOCS) docs.set(doc.source, readCheckoutFile(doc.source));
	return {
		docs,
		cliMain: readCheckoutFile(EXTRA_SOURCES.cliMain),
		packageJson: readCheckoutFile(EXTRA_SOURCES.packageJson),
		openapi: readCheckoutFile(EXTRA_SOURCES.openapi),
		dockerfile: readCheckoutFile(EXTRA_SOURCES.dockerfile),
	};
}

function readCommitted(path: string): string | undefined {
	const absolute = resolve(REPO_ROOT, path);
	return existsSync(absolute) ? readFileSync(absolute, "utf8") : undefined;
}

/**
 * Generated Markdown pages under `DOCS_OUT_DIR` that the current manifest no
 * longer produces. Identified by the banner, so hand-written pages and the
 * plugin-generated `sdk/` + `api/` trees are never touched.
 */
function isOrphanPage(absolute: string, path: string, expected: ReadonlySet<string>): boolean {
	if (!absolute.endsWith(".md") || expected.has(path)) return false;
	return readFileSync(absolute, "utf8").includes(GENERATED_MARKER);
}

function collectOrphans(dir: string, expected: ReadonlySet<string>, out: string[]): void {
	for (const entry of readdirSync(dir, { withFileTypes: true })) {
		const absolute = join(dir, entry.name);
		const path = relative(REPO_ROOT, absolute);
		if (entry.isDirectory()) {
			if (!NON_DERIVED_DIRS.has(entry.name)) collectOrphans(absolute, expected, out);
		} else if (isOrphanPage(absolute, path, expected)) {
			out.push(path);
		}
	}
}

function findOrphans(expected: ReadonlySet<string>): string[] {
	const root = resolve(REPO_ROOT, DOCS_OUT_DIR);
	if (!existsSync(root)) return [];
	const orphans: string[] = [];
	collectOrphans(root, expected, orphans);
	return orphans.sort();
}

function writeFiles(files: readonly GeneratedFile[]): void {
	for (const file of files) {
		const absolute = resolve(REPO_ROOT, file.path);
		mkdirSync(dirname(absolute), { recursive: true });
		writeFileSync(absolute, file.content);
	}
}

function truncate(line: string | undefined): string {
	if (line === undefined) return "(no such line)";
	return line.length > 88 ? `${line.slice(0, 88)}…` : line;
}

/** A short, readable "what changed" report for one drifted file. */
export function diffSummary(generated: string, committed: string): string[] {
	const want = generated.split("\n");
	const have = committed.split("\n");
	const out: string[] = [];
	for (let i = 0; i < Math.max(want.length, have.length) && out.length < DIFF_LINES * 3; i++) {
		if (want[i] === have[i]) continue;
		out.push(`    line ${i + 1}`, `      committed: ${truncate(have[i])}`);
		out.push(`      expected:  ${truncate(want[i])}`);
	}
	if (out.length === 0) out.push("    (files differ only in trailing whitespace)");
	return out;
}

function reportDrift(files: readonly GeneratedFile[], orphans: readonly string[]): number {
	const problems: string[] = [];
	for (const file of files) {
		const committed = readCommitted(file.path);
		if (committed === undefined) {
			problems.push(`  missing: ${file.path}`);
		} else if (committed !== file.content) {
			problems.push(`  stale:   ${file.path}`, ...diffSummary(file.content, committed));
		}
	}
	for (const orphan of orphans) {
		problems.push(`  orphan:  ${orphan} (generated, but no longer in UPSTREAM_DOCS)`);
	}
	if (problems.length === 0) return 0;
	console.error(
		`gen:docs:check FAILED — derived content does not match ` +
			`${UPSTREAM.owner}/${UPSTREAM.repo}@${UPSTREAM.ref}:`,
	);
	for (const problem of problems) console.error(problem);
	console.error("\nfix: bun run sync:upstream   (then commit the result)");
	return 1;
}

function main(): void {
	const checkMode = process.argv.includes("--check");
	ensureCheckout();
	const files = planOutputs(readSources());
	const orphans = findOrphans(new Set(expectedOutputPaths()));

	if (checkMode) {
		const code = reportDrift(files, orphans);
		if (code !== 0) process.exit(code);
		console.log(`gen:docs:check ok (${files.length} derived files match ${UPSTREAM.ref}).`);
		return;
	}

	writeFiles(files);
	for (const orphan of orphans) rmSync(resolve(REPO_ROOT, orphan), { force: true });
	const pruned = orphans.length === 0 ? "" : `, pruned ${orphans.length} orphan(s)`;
	console.log(`wrote ${files.length} derived files from ${UPSTREAM.ref}${pruned}.`);
	for (const file of files) console.log(`  ${file.path}`);
}

if (import.meta.main) main();
